// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package data

import ()

type List struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	UserID int32  `json:"user_id"`
}

type Task struct {
	ID        int64  `json:"id"`
	Text      string `json:"text"`
	Completed bool   `json:"completed"`
	ListID    int32  `json:"list_id"`
}

type User struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
}
